crm/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path("", include(("dashboards.urls", "dashboards"), namespace="dashboards")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboards/urls.py
# Django
from django.urls import path
from django.views.generic.base import View

# Views
from dashboards import views

urlpatterns = [
    path(
        route="login",
        view=views.LoginView.as_view(),
        name="login"
    ),
    path(
        route="logout",
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route="",
        view=views.CapturaView.as_view(),
        name="captura"
    ),
    path(
        route="captura/<int:pk>",
        view=views.CapturaReasignamientoView.as_view(),
        name="captura_reasignamiento"
    ),
    path(
        route="detalle",
        view=views.DetalleClienteView.as_view(),
        name="detalle"
    ),
    path(
        route="<int:pk>",
        view=views.DetalleClienteNuevoView.as_view(),
        name="detallenuevo"
    ),
    path(
        route="operativo_anfitrion",
        view=views.OperativoAnfitrionView.as_view(),
        name="operativo_anfitrion"
    ),
    path(
        route="operativo_asesor",
        view=views.OperativoAsesorView.as_view(),
        name="operativo_asesor"
    ),
    path(
        route="reportes",
        view=views.ReportesView.as_view(),
        name="reportes"
    ),
    path(
        route="reportes_eventos",
        view=views.ReportesEventosView.as_view(),
        name="reportes_eventos"
    ),
    path(
        route="tiempos",
        view=views.TiemposView.as_view(),
        name="tiempos"
    ),
    path(
        route="anulados",
        view=views.AnuladosView.as_view(),
        name="anulados"
    ),
    path(
        route="modernize",
        view=views.ModernizeView.as_view(),
        name="modernize"
    ),
    path(
        route="modernize2",
        view=views.Modernize2View.as_view(),
        name="modernize2"
    ),
    path(
        route="calendar",
        view=views.CalendarView.as_view(),
        name="calendar"
    ),
    path(
        route="calendar/<int:pk>",
        view=views.CalendarDetailView.as_view(),
        name="calendar_detail"
    ),
]

templates/nav.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <a class="navbar-brand">Lead</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarSupportedContent" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                {% if user.groups.get|stringformat:"s" == "Asesor" %}
                <a class="nav-link" href="{% url 'dashboards:captura' %}" role="button" aria-haspopup="true" aria-expanded="false">Captura prospectos</a>
                {% else %}
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Captura prospectos</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'dashboards:captura' %}">Venta</a>
                    <a class="dropdown-item" href="/Compras/CompraCaptura">Compra</a>
                </div>
                {% endif %}
            </li>
            {% if user.groups.get|stringformat:"s" != "Asesor" %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Operativo Anfitrion</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'dashboards:operativo_anfitrion' %}">Venta</a>
                    <a class="dropdown-item" href="/Compras/OperativoAnfitrionCompras">Compra</a>
                    <a class="dropdown-item" href="/SolicitudPeritaje/SeguimientoAnfitrion">Solicitudes de Peritaje</a>
                </div>
            </li>
            {% endif %}

                <li><a class="nav-link" href="{% url 'dashboards:operativo_asesor' %}">Operativo Asesor</a></li>

            {% if user.groups.get|stringformat:"s" != "Asesor" and user.groups.get|stringformat:"s" != "Anfitrión" %}
                <li><a class="nav-link" href="/Compras/OperativoComprador">Operativo Comprador</a></li>
            {% endif %}
            {% if user.groups.get|stringformat:"s" != "Asesor" and user.groups.get|stringformat:"s" != "Anfitrión" %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reportes</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'dashboards:reportes' %}">Venta</a>
                        <a class="dropdown-item" href="/Compras/ReportesCompras">Compra</a>
                        <a class="dropdown-item" href="/SolicitudPeritaje/ReportesSolicitudesPeritaje">Solicitudes Peritaje</a>
                        <a class="dropdown-item" href="{% url 'dashboards:tiempos' %}">Tiempos</a>
                        <a class="dropdown-item" href="{% url 'dashboards:anulados' %}">Anulados</a>
                        <a class="dropdown-item" href="{% url 'dashboards:reportes_eventos' %}">Eventos</a>
                    </div>
                </li>
                {% endif %}
                {% if user.groups.get|stringformat:"s" != "Anfitrión" %}
                <li><a class="nav-link" href="{% if calendario_general %}{% url 'dashboards:calendar' %}{% else %}{% url 'dashboards:calendar_detail' asesor_actual.pk %}{% endif %}">Calendario</a></li>
                {% endif %}
                {% if user.groups.get|stringformat:"s" != "Asesor" and user.groups.get|stringformat:"s" != "Anfitrión" %}
                <li><a class="nav-link" href="/Compras/OperativoPerito">Operativo Perito</a></li>
                {% endif %}
                {% if user.groups.get|stringformat:"s" != "Asesor" and user.groups.get|stringformat:"s" != "Anfitrión" %}
                <li><a class="nav-link" href="/Compras/OperativoTaller">Operativo Taller</a></li>
                {% endif %}
                {% if user.groups.get|stringformat:"s" != "Asesor" and user.groups.get|stringformat:"s" != "Anfitrión" %}
                <li><a class="nav-link" href="http://capnet2.ddns.net:5007/" target="_blank">KPI's</a></li>
                {% endif %}
        </ul>
        <div class="form-inline">
            <button type="button" style="margin-right: 30px; border: none transparent; background-color:transparent; color:white;" onClick="history.back();"><i class="material-icons">reply</i>Atras</button>
        <form action="{% url 'dashboards:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" value="CerrarSesion" style="border: none transparent; background-color:transparent; color:white;"><i class="material-icons">exit_to_app</i>Salir</button>
        </form>    
        </div>
        
    </div>
</nav>